### ISSUE TITLE
How can I Set the ColorData to file

### ISSUE THREAD

**Issue by cnjack** [justinfx/opencolorigo#1]
How can I Set the ColorData to file,I find in oiio but not found

**Comment by justinfx** [comment]
Can you specify which part of the API you are looking to access?
http://opencolorio.org/developers/api/OpenColorIO.html

The README for this project indicates that only part of the OpenColorIO library is wrapped so far, stemming from the fact that I had only needed part of it. Pull requests are welcome to expose more, or I could try and get to it for you if you point out what you need.

**Comment by cnjack** [comment]
may be it is not the API in OpenColorIO 
`
imgDesc := ocio.NewPackedImageDesc(cd, buff.Spec().Width(), buff.Spec().Height(), 3)
err = processor.Apply(imgDesc)
....
imgDesc.Data()
`
I have got the RGBA []float32 but I want get the JPEG(or PNG) file
I have no idea

**Comment by justinfx** [comment]
Oh I see what you are asking for. Yes this is not part of the OpenColorIO API at all. OCIO is not an image transcoding library. It only handles color processing to raw pixel data. You are meant to use something else to get it in and out of that RGB(A) pixel format. 

My other bindings library, [OpenImageiGO](https://godoc.org/github.com/justinfx/openimageigo) can be used for this, and it even has integrated OCIO to do all the color transformation work in the same library. Or you can even just use the Go stdlib image package to convert your raw RGB to a jpeg.

**Comment by cnjack** [comment]
yep, I just use the OpenImageIGO but not find the function I try to use the Go Image library to do this,maybe it work maybe I will also get your help, thx~~~

**Comment by justinfx** [comment]
That being said...it might be a nice convenience to have this OpenColoriGo library provide a function for giving you an `image.RGBA` that can then be encoded.

**Comment by justinfx** [comment]
I've thrown together an example program to help you do this with just the stdlib:
https://gist.github.com/justinfx/4ae8884131c4fbbef373cfd7f7ef259c

Let me know if this fixes your issue? You should be able to convert your pixels and encode a jpeg with this.

**Comment by cnjack** [comment]
OK,I have try to write by Golang `image` Lab ,and there has been progress, I will try your solution tomorrow, It is 00.24 😴

**Comment by justinfx** [comment]
Closing this as I feel the example I have given should solve your question.
